spring:
  jpa:
    show-sql: false

app:
  datasource:
    verification:
      url: ${VERIFICATION_DB_URL}
      username: ${VERIFICATION_DB_USER}
      password: ${VERIFICATION_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
